version: "3.5"
services:

  php:
    build:
      context: ./
      dockerfile: docker/apache_php/php8.dockerfile
    container_name: evolved5g_pilot_php
    user: "${DOCKER_USER_ID}:${DOCKER_GROUP_ID}" # this is the Laravel user. We need to set it
    # this way, so that the permissions are applied correctly.
    ports:
      - "89:80"
    volumes:
      - .:/var/www/html
      - ~/.composer/auth.json:/root/.composer/auth.json
    networks:
      - docker_evolved5g_net
  db:
    build:
      context: docker/db
    container_name: evolved5g_pilot_db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3316:3306"
    volumes:
      - mydata:/var/lib/mysql
    networks:
      - docker_evolved5g_net

  phpmyadmin:
    depends_on:
      - db
      - php
    container_name: evolved5g_pilot_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8089:80"
    environment:
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 128M
      PMA_HOST: db
    networks:
      - docker_evolved5g_net

  composer:
    container_name: evolved5g_pilot_composer
    build:
      context: ./docker/utils
      dockerfile: composer.dockerfile
      args:
        DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
    volumes:
      - .:/var/www/html
    networks:
      - docker_evolved5g_net

  artisan:
    container_name: evolved5g_pilot_artisan
    build:
      context: ./
      dockerfile: docker/apache_php/php8.dockerfile
      args:
        DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
    volumes:
      - .:/var/www/html
    networks:
      - docker_evolved5g_net
    depends_on:
      - php
    entrypoint: [ "php", "/var/www/html/artisan" ]

  npm:
    build:
      context: .
      dockerfile: docker/utils/npm.dockerfile
    container_name: evolved5g_pilot_npm
    working_dir: /var/www/html
    entrypoint: [ "npm" ]
    volumes:
      - .:/var/www/html
    networks:
      - docker_evolved5g_net
    depends_on:
      - php

  supervisor:
    container_name: supervisor
    build:
      context: ./
      dockerfile: docker/Dockerfile.supervisor
    restart: unless-stopped
    environment:
      - APP_ROOT=/var/www/html
      - QUEUE_DRIVER=${QUEUE_CONNECTION}
      - OPTIONS=${QUEUE_OPTIONS}
      - NUM_PROCS=${NUM_PROCS}
    networks:
      - docker_evolved5g_net
    depends_on:
      - php
      - db


volumes:
  mydata:

networks:
  docker_evolved5g_net:
    external: false
    name: docker_evolved5g_net
